/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    streetAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    ward?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    district?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    cityProvince?: string | null;
}

/**
 * Check if a given object implements the Address interface.
 */
export function instanceOfAddress(value: object): value is Address {
    return true;
}

export function AddressFromJSON(json: any): Address {
    return AddressFromJSONTyped(json, false);
}

export function AddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): Address {
    if (json == null) {
        return json;
    }
    return {
        
        'streetAddress': json['streetAddress'] == null ? undefined : json['streetAddress'],
        'ward': json['ward'] == null ? undefined : json['ward'],
        'district': json['district'] == null ? undefined : json['district'],
        'cityProvince': json['cityProvince'] == null ? undefined : json['cityProvince'],
    };
}

export function AddressToJSON(json: any): Address {
    return AddressToJSONTyped(json, false);
}

export function AddressToJSONTyped(value?: Address | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'streetAddress': value['streetAddress'],
        'ward': value['ward'],
        'district': value['district'],
        'cityProvince': value['cityProvince'],
    };
}

