/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankingInfor
 */
export interface BankingInfor {
    /**
     * 
     * @type {string}
     * @memberof BankingInfor
     */
    bankCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BankingInfor
     */
    bankTransactionId?: string | null;
}

/**
 * Check if a given object implements the BankingInfor interface.
 */
export function instanceOfBankingInfor(value: object): value is BankingInfor {
    return true;
}

export function BankingInforFromJSON(json: any): BankingInfor {
    return BankingInforFromJSONTyped(json, false);
}

export function BankingInforFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankingInfor {
    if (json == null) {
        return json;
    }
    return {
        
        'bankCode': json['bankCode'] == null ? undefined : json['bankCode'],
        'bankTransactionId': json['bankTransactionId'] == null ? undefined : json['bankTransactionId'],
    };
}

export function BankingInforToJSON(json: any): BankingInfor {
    return BankingInforToJSONTyped(json, false);
}

export function BankingInforToJSONTyped(value?: BankingInfor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bankCode': value['bankCode'],
        'bankTransactionId': value['bankTransactionId'],
    };
}

