/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryDetailsDto } from './CategoryDetailsDto';
import {
    CategoryDetailsDtoFromJSON,
    CategoryDetailsDtoFromJSONTyped,
    CategoryDetailsDtoToJSON,
    CategoryDetailsDtoToJSONTyped,
} from './CategoryDetailsDto';

/**
 * 
 * @export
 * @interface CategoryDetailsDtoPaginationList
 */
export interface CategoryDetailsDtoPaginationList {
    /**
     * 
     * @type {Array<CategoryDetailsDto>}
     * @memberof CategoryDetailsDtoPaginationList
     */
    items?: Array<CategoryDetailsDto> | null;
    /**
     * 
     * @type {number}
     * @memberof CategoryDetailsDtoPaginationList
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryDetailsDtoPaginationList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryDetailsDtoPaginationList
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryDetailsDtoPaginationList
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CategoryDetailsDtoPaginationList
     */
    readonly hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CategoryDetailsDtoPaginationList
     */
    readonly hasNextPage?: boolean;
}

/**
 * Check if a given object implements the CategoryDetailsDtoPaginationList interface.
 */
export function instanceOfCategoryDetailsDtoPaginationList(value: object): value is CategoryDetailsDtoPaginationList {
    return true;
}

export function CategoryDetailsDtoPaginationListFromJSON(json: any): CategoryDetailsDtoPaginationList {
    return CategoryDetailsDtoPaginationListFromJSONTyped(json, false);
}

export function CategoryDetailsDtoPaginationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryDetailsDtoPaginationList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CategoryDetailsDtoFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

export function CategoryDetailsDtoPaginationListToJSON(json: any): CategoryDetailsDtoPaginationList {
    return CategoryDetailsDtoPaginationListToJSONTyped(json, false);
}

export function CategoryDetailsDtoPaginationListToJSONTyped(value?: Omit<CategoryDetailsDtoPaginationList, 'totalPages'|'hasPreviousPage'|'hasNextPage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CategoryDetailsDtoToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
    };
}

