/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryCreateDto
 */
export interface CategoryCreateDto {
    /**
     * 
     * @type {string}
     * @memberof CategoryCreateDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CategoryCreateDto
     */
    createdDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CategoryCreateDto
     */
    modifiedDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CategoryCreateDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CategoryCreateDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CategoryCreateDto
     */
    parentCategoryId?: string | null;
}

/**
 * Check if a given object implements the CategoryCreateDto interface.
 */
export function instanceOfCategoryCreateDto(value: object): value is CategoryCreateDto {
    return true;
}

export function CategoryCreateDtoFromJSON(json: any): CategoryCreateDto {
    return CategoryCreateDtoFromJSONTyped(json, false);
}

export function CategoryCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'modifiedDate': json['modifiedDate'] == null ? undefined : (new Date(json['modifiedDate'])),
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'parentCategoryId': json['parentCategoryId'] == null ? undefined : json['parentCategoryId'],
    };
}

export function CategoryCreateDtoToJSON(json: any): CategoryCreateDto {
    return CategoryCreateDtoToJSONTyped(json, false);
}

export function CategoryCreateDtoToJSONTyped(value?: CategoryCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
        'modifiedDate': value['modifiedDate'] == null ? undefined : ((value['modifiedDate'] as any).toISOString()),
        'name': value['name'],
        'description': value['description'],
        'parentCategoryId': value['parentCategoryId'],
    };
}

