/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePaymentDto
 */
export interface CreatePaymentDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentDto
     */
    orderId?: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentDto
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentDto
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CreatePaymentDto interface.
 */
export function instanceOfCreatePaymentDto(value: object): value is CreatePaymentDto {
    return true;
}

export function CreatePaymentDtoFromJSON(json: any): CreatePaymentDto {
    return CreatePaymentDtoFromJSONTyped(json, false);
}

export function CreatePaymentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreatePaymentDtoToJSON(json: any): CreatePaymentDto {
    return CreatePaymentDtoToJSONTyped(json, false);
}

export function CreatePaymentDtoToJSONTyped(value?: CreatePaymentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'totalAmount': value['totalAmount'],
        'description': value['description'],
    };
}

