/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { CreateOrderItemDto } from './CreateOrderItemDto';
import {
    CreateOrderItemDtoFromJSON,
    CreateOrderItemDtoFromJSONTyped,
    CreateOrderItemDtoToJSON,
    CreateOrderItemDtoToJSONTyped,
} from './CreateOrderItemDto';
import type { PaymentMethod } from './PaymentMethod';
import {
    PaymentMethodFromJSON,
    PaymentMethodFromJSONTyped,
    PaymentMethodToJSON,
    PaymentMethodToJSONTyped,
} from './PaymentMethod';

/**
 * 
 * @export
 * @interface CreateOrderCommand
 */
export interface CreateOrderCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateOrderCommand
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderCommand
     */
    customerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderCommand
     */
    shippingPhoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderCommand
     */
    customerId?: string;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof CreateOrderCommand
     */
    paymentMethod?: PaymentMethod;
    /**
     * 
     * @type {Address}
     * @memberof CreateOrderCommand
     */
    shippingAddress?: Address;
    /**
     * 
     * @type {Array<CreateOrderItemDto>}
     * @memberof CreateOrderCommand
     */
    orderItems?: Array<CreateOrderItemDto> | null;
}



/**
 * Check if a given object implements the CreateOrderCommand interface.
 */
export function instanceOfCreateOrderCommand(value: object): value is CreateOrderCommand {
    return true;
}

export function CreateOrderCommandFromJSON(json: any): CreateOrderCommand {
    return CreateOrderCommandFromJSONTyped(json, false);
}

export function CreateOrderCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'customerName': json['customerName'] == null ? undefined : json['customerName'],
        'shippingPhoneNumber': json['shippingPhoneNumber'] == null ? undefined : json['shippingPhoneNumber'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'paymentMethod': json['paymentMethod'] == null ? undefined : PaymentMethodFromJSON(json['paymentMethod']),
        'shippingAddress': json['shippingAddress'] == null ? undefined : AddressFromJSON(json['shippingAddress']),
        'orderItems': json['orderItems'] == null ? undefined : ((json['orderItems'] as Array<any>).map(CreateOrderItemDtoFromJSON)),
    };
}

export function CreateOrderCommandToJSON(json: any): CreateOrderCommand {
    return CreateOrderCommandToJSONTyped(json, false);
}

export function CreateOrderCommandToJSONTyped(value?: CreateOrderCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'customerName': value['customerName'],
        'shippingPhoneNumber': value['shippingPhoneNumber'],
        'customerId': value['customerId'],
        'paymentMethod': PaymentMethodToJSON(value['paymentMethod']),
        'shippingAddress': AddressToJSON(value['shippingAddress']),
        'orderItems': value['orderItems'] == null ? undefined : ((value['orderItems'] as Array<any>).map(CreateOrderItemDtoToJSON)),
    };
}

