/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderItemDto
 */
export interface CreateOrderItemDto {
    /**
     * 
     * @type {string}
     * @memberof CreateOrderItemDto
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderItemDto
     */
    productVariantId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateOrderItemDto
     */
    quantity?: number;
}

/**
 * Check if a given object implements the CreateOrderItemDto interface.
 */
export function instanceOfCreateOrderItemDto(value: object): value is CreateOrderItemDto {
    return true;
}

export function CreateOrderItemDtoFromJSON(json: any): CreateOrderItemDto {
    return CreateOrderItemDtoFromJSONTyped(json, false);
}

export function CreateOrderItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'] == null ? undefined : json['productId'],
        'productVariantId': json['productVariantId'] == null ? undefined : json['productVariantId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function CreateOrderItemDtoToJSON(json: any): CreateOrderItemDto {
    return CreateOrderItemDtoToJSONTyped(json, false);
}

export function CreateOrderItemDtoToJSONTyped(value?: CreateOrderItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'productVariantId': value['productVariantId'],
        'quantity': value['quantity'],
    };
}

