/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCartCommand
 */
export interface CreateCartCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateCartCommand
     */
    customerId?: string;
}

/**
 * Check if a given object implements the CreateCartCommand interface.
 */
export function instanceOfCreateCartCommand(value: object): value is CreateCartCommand {
    return true;
}

export function CreateCartCommandFromJSON(json: any): CreateCartCommand {
    return CreateCartCommandFromJSONTyped(json, false);
}

export function CreateCartCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCartCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
    };
}

export function CreateCartCommandToJSON(json: any): CreateCartCommand {
    return CreateCartCommandToJSONTyped(json, false);
}

export function CreateCartCommandToJSONTyped(value?: CreateCartCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customerId': value['customerId'],
    };
}

