/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerDetailsDto } from './CustomerDetailsDto';
import {
    CustomerDetailsDtoFromJSON,
    CustomerDetailsDtoFromJSONTyped,
    CustomerDetailsDtoToJSON,
    CustomerDetailsDtoToJSONTyped,
} from './CustomerDetailsDto';

/**
 * 
 * @export
 * @interface CustomerDetailsDtoPaginationList
 */
export interface CustomerDetailsDtoPaginationList {
    /**
     * 
     * @type {Array<CustomerDetailsDto>}
     * @memberof CustomerDetailsDtoPaginationList
     */
    items?: Array<CustomerDetailsDto> | null;
    /**
     * 
     * @type {number}
     * @memberof CustomerDetailsDtoPaginationList
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerDetailsDtoPaginationList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerDetailsDtoPaginationList
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerDetailsDtoPaginationList
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerDetailsDtoPaginationList
     */
    readonly hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerDetailsDtoPaginationList
     */
    readonly hasNextPage?: boolean;
}

/**
 * Check if a given object implements the CustomerDetailsDtoPaginationList interface.
 */
export function instanceOfCustomerDetailsDtoPaginationList(value: object): value is CustomerDetailsDtoPaginationList {
    return true;
}

export function CustomerDetailsDtoPaginationListFromJSON(json: any): CustomerDetailsDtoPaginationList {
    return CustomerDetailsDtoPaginationListFromJSONTyped(json, false);
}

export function CustomerDetailsDtoPaginationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerDetailsDtoPaginationList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CustomerDetailsDtoFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

export function CustomerDetailsDtoPaginationListToJSON(json: any): CustomerDetailsDtoPaginationList {
    return CustomerDetailsDtoPaginationListToJSONTyped(json, false);
}

export function CustomerDetailsDtoPaginationListToJSONTyped(value?: Omit<CustomerDetailsDtoPaginationList, 'totalPages'|'hasPreviousPage'|'hasNextPage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CustomerDetailsDtoToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
    };
}

