/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerDetailsDto
 */
export interface CustomerDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailsDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomerDetailsDto
     */
    createdDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerDetailsDto
     */
    modifiedDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailsDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailsDto
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailsDto
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailsDto
     */
    lastName?: string | null;
}

/**
 * Check if a given object implements the CustomerDetailsDto interface.
 */
export function instanceOfCustomerDetailsDto(value: object): value is CustomerDetailsDto {
    return true;
}

export function CustomerDetailsDtoFromJSON(json: any): CustomerDetailsDto {
    return CustomerDetailsDtoFromJSONTyped(json, false);
}

export function CustomerDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'modifiedDate': json['modifiedDate'] == null ? undefined : (new Date(json['modifiedDate'])),
        'email': json['email'] == null ? undefined : json['email'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
    };
}

export function CustomerDetailsDtoToJSON(json: any): CustomerDetailsDto {
    return CustomerDetailsDtoToJSONTyped(json, false);
}

export function CustomerDetailsDtoToJSONTyped(value?: CustomerDetailsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
        'modifiedDate': value['modifiedDate'] == null ? undefined : ((value['modifiedDate'] as any).toISOString()),
        'email': value['email'],
        'userName': value['userName'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

