/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdentityUser
 */
export interface IdentityUser {
    /**
     * 
     * @type {string}
     * @memberof IdentityUser
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUser
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUser
     */
    normalizedUserName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUser
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUser
     */
    normalizedEmail?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityUser
     */
    emailConfirmed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IdentityUser
     */
    passwordHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUser
     */
    securityStamp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUser
     */
    concurrencyStamp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUser
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityUser
     */
    phoneNumberConfirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityUser
     */
    twoFactorEnabled?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof IdentityUser
     */
    lockoutEnd?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityUser
     */
    lockoutEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof IdentityUser
     */
    accessFailedCount?: number;
}

/**
 * Check if a given object implements the IdentityUser interface.
 */
export function instanceOfIdentityUser(value: object): value is IdentityUser {
    return true;
}

export function IdentityUserFromJSON(json: any): IdentityUser {
    return IdentityUserFromJSONTyped(json, false);
}

export function IdentityUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'normalizedUserName': json['normalizedUserName'] == null ? undefined : json['normalizedUserName'],
        'email': json['email'] == null ? undefined : json['email'],
        'normalizedEmail': json['normalizedEmail'] == null ? undefined : json['normalizedEmail'],
        'emailConfirmed': json['emailConfirmed'] == null ? undefined : json['emailConfirmed'],
        'passwordHash': json['passwordHash'] == null ? undefined : json['passwordHash'],
        'securityStamp': json['securityStamp'] == null ? undefined : json['securityStamp'],
        'concurrencyStamp': json['concurrencyStamp'] == null ? undefined : json['concurrencyStamp'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'phoneNumberConfirmed': json['phoneNumberConfirmed'] == null ? undefined : json['phoneNumberConfirmed'],
        'twoFactorEnabled': json['twoFactorEnabled'] == null ? undefined : json['twoFactorEnabled'],
        'lockoutEnd': json['lockoutEnd'] == null ? undefined : (new Date(json['lockoutEnd'])),
        'lockoutEnabled': json['lockoutEnabled'] == null ? undefined : json['lockoutEnabled'],
        'accessFailedCount': json['accessFailedCount'] == null ? undefined : json['accessFailedCount'],
    };
}

export function IdentityUserToJSON(json: any): IdentityUser {
    return IdentityUserToJSONTyped(json, false);
}

export function IdentityUserToJSONTyped(value?: IdentityUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userName': value['userName'],
        'normalizedUserName': value['normalizedUserName'],
        'email': value['email'],
        'normalizedEmail': value['normalizedEmail'],
        'emailConfirmed': value['emailConfirmed'],
        'passwordHash': value['passwordHash'],
        'securityStamp': value['securityStamp'],
        'concurrencyStamp': value['concurrencyStamp'],
        'phoneNumber': value['phoneNumber'],
        'phoneNumberConfirmed': value['phoneNumberConfirmed'],
        'twoFactorEnabled': value['twoFactorEnabled'],
        'lockoutEnd': value['lockoutEnd'] == null ? undefined : ((value['lockoutEnd'] as any).toISOString()),
        'lockoutEnabled': value['lockoutEnabled'],
        'accessFailedCount': value['accessFailedCount'],
    };
}

