/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseCode } from './ResponseCode';
import {
    ResponseCodeFromJSON,
    ResponseCodeFromJSONTyped,
    ResponseCodeToJSON,
    ResponseCodeToJSONTyped,
} from './ResponseCode';

/**
 * 
 * @export
 * @interface PaymentResponse
 */
export interface PaymentResponse {
    /**
     * 
     * @type {ResponseCode}
     * @memberof PaymentResponse
     */
    code?: ResponseCode;
    /**
     * 
     * @type {string}
     * @memberof PaymentResponse
     */
    description?: string | null;
}



/**
 * Check if a given object implements the PaymentResponse interface.
 */
export function instanceOfPaymentResponse(value: object): value is PaymentResponse {
    return true;
}

export function PaymentResponseFromJSON(json: any): PaymentResponse {
    return PaymentResponseFromJSONTyped(json, false);
}

export function PaymentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResponseCodeFromJSON(json['code']),
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function PaymentResponseToJSON(json: any): PaymentResponse {
    return PaymentResponseToJSONTyped(json, false);
}

export function PaymentResponseToJSONTyped(value?: PaymentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResponseCodeToJSON(value['code']),
        'description': value['description'],
    };
}

