/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductImageCreateDto
 */
export interface ProductImageCreateDto {
    /**
     * 
     * @type {string}
     * @memberof ProductImageCreateDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductImageCreateDto
     */
    createdDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductImageCreateDto
     */
    modifiedDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ProductImageCreateDto
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductImageCreateDto
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductImageCreateDto
     */
    altText?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductImageCreateDto
     */
    sortOrder?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductImageCreateDto
     */
    isPrimary?: boolean;
}

/**
 * Check if a given object implements the ProductImageCreateDto interface.
 */
export function instanceOfProductImageCreateDto(value: object): value is ProductImageCreateDto {
    return true;
}

export function ProductImageCreateDtoFromJSON(json: any): ProductImageCreateDto {
    return ProductImageCreateDtoFromJSONTyped(json, false);
}

export function ProductImageCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductImageCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'modifiedDate': json['modifiedDate'] == null ? undefined : (new Date(json['modifiedDate'])),
        'productId': json['productId'] == null ? undefined : json['productId'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'altText': json['altText'] == null ? undefined : json['altText'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
        'isPrimary': json['isPrimary'] == null ? undefined : json['isPrimary'],
    };
}

export function ProductImageCreateDtoToJSON(json: any): ProductImageCreateDto {
    return ProductImageCreateDtoToJSONTyped(json, false);
}

export function ProductImageCreateDtoToJSONTyped(value?: ProductImageCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
        'modifiedDate': value['modifiedDate'] == null ? undefined : ((value['modifiedDate'] as any).toISOString()),
        'productId': value['productId'],
        'imageUrl': value['imageUrl'],
        'altText': value['altText'],
        'sortOrder': value['sortOrder'],
        'isPrimary': value['isPrimary'],
    };
}

