/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductCreateDto
 */
export interface ProductCreateDto {
    /**
     * 
     * @type {string}
     * @memberof ProductCreateDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductCreateDto
     */
    createdDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductCreateDto
     */
    modifiedDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ProductCreateDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductCreateDto
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateDto
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductCreateDto
     */
    sku?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductCreateDto
     */
    categoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductCreateDto
     */
    details?: string | null;
}

/**
 * Check if a given object implements the ProductCreateDto interface.
 */
export function instanceOfProductCreateDto(value: object): value is ProductCreateDto {
    return true;
}

export function ProductCreateDtoFromJSON(json: any): ProductCreateDto {
    return ProductCreateDtoFromJSONTyped(json, false);
}

export function ProductCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'modifiedDate': json['modifiedDate'] == null ? undefined : (new Date(json['modifiedDate'])),
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'sku': json['sku'] == null ? undefined : json['sku'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function ProductCreateDtoToJSON(json: any): ProductCreateDto {
    return ProductCreateDtoToJSONTyped(json, false);
}

export function ProductCreateDtoToJSONTyped(value?: ProductCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
        'modifiedDate': value['modifiedDate'] == null ? undefined : ((value['modifiedDate'] as any).toISOString()),
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'sku': value['sku'],
        'categoryId': value['categoryId'],
        'details': value['details'],
    };
}

