/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductImageDetailsDto } from './ProductImageDetailsDto';
import {
    ProductImageDetailsDtoFromJSON,
    ProductImageDetailsDtoFromJSONTyped,
    ProductImageDetailsDtoToJSON,
    ProductImageDetailsDtoToJSONTyped,
} from './ProductImageDetailsDto';

/**
 * 
 * @export
 * @interface ProductsInCategoryDto
 */
export interface ProductsInCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof ProductsInCategoryDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductsInCategoryDto
     */
    createdDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductsInCategoryDto
     */
    modifiedDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ProductsInCategoryDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductsInCategoryDto
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductsInCategoryDto
     */
    readonly price?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductsInCategoryDto
     */
    readonly details?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductsInCategoryDto
     */
    readonly categoryId?: string | null;
    /**
     * 
     * @type {Array<ProductImageDetailsDto>}
     * @memberof ProductsInCategoryDto
     */
    images?: Array<ProductImageDetailsDto> | null;
}

/**
 * Check if a given object implements the ProductsInCategoryDto interface.
 */
export function instanceOfProductsInCategoryDto(value: object): value is ProductsInCategoryDto {
    return true;
}

export function ProductsInCategoryDtoFromJSON(json: any): ProductsInCategoryDto {
    return ProductsInCategoryDtoFromJSONTyped(json, false);
}

export function ProductsInCategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsInCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'modifiedDate': json['modifiedDate'] == null ? undefined : (new Date(json['modifiedDate'])),
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'details': json['details'] == null ? undefined : json['details'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ProductImageDetailsDtoFromJSON)),
    };
}

export function ProductsInCategoryDtoToJSON(json: any): ProductsInCategoryDto {
    return ProductsInCategoryDtoToJSONTyped(json, false);
}

export function ProductsInCategoryDtoToJSONTyped(value?: Omit<ProductsInCategoryDto, 'price'|'details'|'categoryId'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
        'modifiedDate': value['modifiedDate'] == null ? undefined : ((value['modifiedDate'] as any).toISOString()),
        'name': value['name'],
        'description': value['description'],
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ProductImageDetailsDtoToJSON)),
    };
}

