/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface ProductImage
 */
export interface ProductImage {
    /**
     * 
     * @type {string}
     * @memberof ProductImage
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductImage
     */
    createdDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductImage
     */
    modifiedDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ProductImage
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductImage
     */
    altText?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductImage
     */
    sortOrder?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductImage
     */
    isPrimary?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductImage
     */
    productId?: string;
    /**
     * 
     * @type {Product}
     * @memberof ProductImage
     */
    product?: Product;
}

/**
 * Check if a given object implements the ProductImage interface.
 */
export function instanceOfProductImage(value: object): value is ProductImage {
    return true;
}

export function ProductImageFromJSON(json: any): ProductImage {
    return ProductImageFromJSONTyped(json, false);
}

export function ProductImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductImage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'modifiedDate': json['modifiedDate'] == null ? undefined : (new Date(json['modifiedDate'])),
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'altText': json['altText'] == null ? undefined : json['altText'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
        'isPrimary': json['isPrimary'] == null ? undefined : json['isPrimary'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'product': json['product'] == null ? undefined : ProductFromJSON(json['product']),
    };
}

export function ProductImageToJSON(json: any): ProductImage {
    return ProductImageToJSONTyped(json, false);
}

export function ProductImageToJSONTyped(value?: ProductImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
        'modifiedDate': value['modifiedDate'] == null ? undefined : ((value['modifiedDate'] as any).toISOString()),
        'imageUrl': value['imageUrl'],
        'altText': value['altText'],
        'sortOrder': value['sortOrder'],
        'isPrimary': value['isPrimary'],
        'productId': value['productId'],
        'product': ProductToJSON(value['product']),
    };
}

