/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface ProductVariant
 */
export interface ProductVariant {
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductVariant
     */
    createdDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductVariant
     */
    modifiedDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    variantType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    sku?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductVariant
     */
    stockQuantity?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductVariant
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    productId?: string;
    /**
     * 
     * @type {Product}
     * @memberof ProductVariant
     */
    product?: Product;
}

/**
 * Check if a given object implements the ProductVariant interface.
 */
export function instanceOfProductVariant(value: object): value is ProductVariant {
    return true;
}

export function ProductVariantFromJSON(json: any): ProductVariant {
    return ProductVariantFromJSONTyped(json, false);
}

export function ProductVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductVariant {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'modifiedDate': json['modifiedDate'] == null ? undefined : (new Date(json['modifiedDate'])),
        'variantType': json['variantType'] == null ? undefined : json['variantType'],
        'name': json['name'] == null ? undefined : json['name'],
        'sku': json['sku'] == null ? undefined : json['sku'],
        'stockQuantity': json['stockQuantity'] == null ? undefined : json['stockQuantity'],
        'price': json['price'] == null ? undefined : json['price'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'product': json['product'] == null ? undefined : ProductFromJSON(json['product']),
    };
}

export function ProductVariantToJSON(json: any): ProductVariant {
    return ProductVariantToJSONTyped(json, false);
}

export function ProductVariantToJSONTyped(value?: ProductVariant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
        'modifiedDate': value['modifiedDate'] == null ? undefined : ((value['modifiedDate'] as any).toISOString()),
        'variantType': value['variantType'],
        'name': value['name'],
        'sku': value['sku'],
        'stockQuantity': value['stockQuantity'],
        'price': value['price'],
        'productId': value['productId'],
        'product': ProductToJSON(value['product']),
    };
}

