/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ResponseCode = {
    NUMBER_0: 0,
    NUMBER_7: 7,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_11: 11,
    NUMBER_12: 12,
    NUMBER_13: 13,
    NUMBER_24: 24,
    NUMBER_51: 51,
    NUMBER_65: 65,
    NUMBER_75: 75,
    NUMBER_79: 79,
    NUMBER_99: 99
} as const;
export type ResponseCode = typeof ResponseCode[keyof typeof ResponseCode];


export function instanceOfResponseCode(value: any): boolean {
    for (const key in ResponseCode) {
        if (Object.prototype.hasOwnProperty.call(ResponseCode, key)) {
            if (ResponseCode[key as keyof typeof ResponseCode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResponseCodeFromJSON(json: any): ResponseCode {
    return ResponseCodeFromJSONTyped(json, false);
}

export function ResponseCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseCode {
    return json as ResponseCode;
}

export function ResponseCodeToJSON(value?: ResponseCode | null): any {
    return value as any;
}

export function ResponseCodeToJSONTyped(value: any, ignoreDiscriminator: boolean): ResponseCode {
    return value as ResponseCode;
}

