/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubCategoriesDto
 */
export interface SubCategoriesDto {
    /**
     * 
     * @type {string}
     * @memberof SubCategoriesDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SubCategoriesDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubCategoriesDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubCategoriesDto
     */
    parentCategoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubCategoriesDto
     */
    parentCategoryName?: string | null;
}

/**
 * Check if a given object implements the SubCategoriesDto interface.
 */
export function instanceOfSubCategoriesDto(value: object): value is SubCategoriesDto {
    return true;
}

export function SubCategoriesDtoFromJSON(json: any): SubCategoriesDto {
    return SubCategoriesDtoFromJSONTyped(json, false);
}

export function SubCategoriesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubCategoriesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'parentCategoryId': json['parentCategoryId'] == null ? undefined : json['parentCategoryId'],
        'parentCategoryName': json['parentCategoryName'] == null ? undefined : json['parentCategoryName'],
    };
}

export function SubCategoriesDtoToJSON(json: any): SubCategoriesDto {
    return SubCategoriesDtoToJSONTyped(json, false);
}

export function SubCategoriesDtoToJSONTyped(value?: SubCategoriesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'parentCategoryId': value['parentCategoryId'],
        'parentCategoryName': value['parentCategoryName'],
    };
}

