/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TransactionStatusCode = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_9: 9
} as const;
export type TransactionStatusCode = typeof TransactionStatusCode[keyof typeof TransactionStatusCode];


export function instanceOfTransactionStatusCode(value: any): boolean {
    for (const key in TransactionStatusCode) {
        if (Object.prototype.hasOwnProperty.call(TransactionStatusCode, key)) {
            if (TransactionStatusCode[key as keyof typeof TransactionStatusCode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TransactionStatusCodeFromJSON(json: any): TransactionStatusCode {
    return TransactionStatusCodeFromJSONTyped(json, false);
}

export function TransactionStatusCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionStatusCode {
    return json as TransactionStatusCode;
}

export function TransactionStatusCodeToJSON(value?: TransactionStatusCode | null): any {
    return value as any;
}

export function TransactionStatusCodeToJSONTyped(value: any, ignoreDiscriminator: boolean): TransactionStatusCode {
    return value as TransactionStatusCode;
}

