/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCartItemCommand
 */
export interface UpdateCartItemCommand {
    /**
     * 
     * @type {number}
     * @memberof UpdateCartItemCommand
     */
    quantity?: number;
}

/**
 * Check if a given object implements the UpdateCartItemCommand interface.
 */
export function instanceOfUpdateCartItemCommand(value: object): value is UpdateCartItemCommand {
    return true;
}

export function UpdateCartItemCommandFromJSON(json: any): UpdateCartItemCommand {
    return UpdateCartItemCommandFromJSONTyped(json, false);
}

export function UpdateCartItemCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCartItemCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function UpdateCartItemCommandToJSON(json: any): UpdateCartItemCommand {
    return UpdateCartItemCommandToJSONTyped(json, false);
}

export function UpdateCartItemCommandToJSONTyped(value?: UpdateCartItemCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
    };
}

