/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentStatus } from './PaymentStatus';
import {
    PaymentStatusFromJSON,
    PaymentStatusFromJSONTyped,
    PaymentStatusToJSON,
    PaymentStatusToJSONTyped,
} from './PaymentStatus';

/**
 * 
 * @export
 * @interface UpdateOrderCommand
 */
export interface UpdateOrderCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateOrderCommand
     */
    transactionId?: string | null;
    /**
     * 
     * @type {PaymentStatus}
     * @memberof UpdateOrderCommand
     */
    paymentStatus?: PaymentStatus;
}



/**
 * Check if a given object implements the UpdateOrderCommand interface.
 */
export function instanceOfUpdateOrderCommand(value: object): value is UpdateOrderCommand {
    return true;
}

export function UpdateOrderCommandFromJSON(json: any): UpdateOrderCommand {
    return UpdateOrderCommandFromJSONTyped(json, false);
}

export function UpdateOrderCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrderCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
        'paymentStatus': json['paymentStatus'] == null ? undefined : PaymentStatusFromJSON(json['paymentStatus']),
    };
}

export function UpdateOrderCommandToJSON(json: any): UpdateOrderCommand {
    return UpdateOrderCommandToJSONTyped(json, false);
}

export function UpdateOrderCommandToJSONTyped(value?: UpdateOrderCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactionId': value['transactionId'],
        'paymentStatus': PaymentStatusToJSON(value['paymentStatus']),
    };
}

