/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProductCommand
 */
export interface UpdateProductCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateProductCommand
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductCommand
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductCommand
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductCommand
     */
    details?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductCommand
     */
    totalQuantity?: number | null;
}

/**
 * Check if a given object implements the UpdateProductCommand interface.
 */
export function instanceOfUpdateProductCommand(value: object): value is UpdateProductCommand {
    return true;
}

export function UpdateProductCommandFromJSON(json: any): UpdateProductCommand {
    return UpdateProductCommandFromJSONTyped(json, false);
}

export function UpdateProductCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProductCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'details': json['details'] == null ? undefined : json['details'],
        'totalQuantity': json['totalQuantity'] == null ? undefined : json['totalQuantity'],
    };
}

export function UpdateProductCommandToJSON(json: any): UpdateProductCommand {
    return UpdateProductCommandToJSONTyped(json, false);
}

export function UpdateProductCommandToJSONTyped(value?: UpdateProductCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'details': value['details'],
        'totalQuantity': value['totalQuantity'],
    };
}

