/* tslint:disable */
/* eslint-disable */
/**
 * NashLux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePaymentDto,
  PaymentResult,
} from '../models/index';
import {
    CreatePaymentDtoFromJSON,
    CreatePaymentDtoToJSON,
    PaymentResultFromJSON,
    PaymentResultToJSON,
} from '../models/index';

export interface ApiV1VnpayPaymentUrlPostRequest {
    createPaymentDto?: CreatePaymentDto;
}

/**
 * 
 */
export class VnpayApi extends runtime.BaseAPI {

    /**
     */
    async apiV1VnpayCallbackGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/vnpay/callback`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentResultFromJSON(jsonValue));
    }

    /**
     */
    async apiV1VnpayCallbackGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentResult> {
        const response = await this.apiV1VnpayCallbackGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1VnpayPaymentUrlPostRaw(requestParameters: ApiV1VnpayPaymentUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/vnpay/payment-url`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePaymentDtoToJSON(requestParameters['createPaymentDto']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiV1VnpayPaymentUrlPost(requestParameters: ApiV1VnpayPaymentUrlPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiV1VnpayPaymentUrlPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
